### ISSUE TITLE
Is there some bug caused to OOM?

### ISSUE THREAD

**Issue by storyandwine** [zjlxgxz/DynamicPPE#2]
Hi,
Thanks for your excellent work!
But I have some trouble after running the example code, I will be much appreciative if you can give me some advice.

Outputs are follows:
snapshot 1 #edges 465 cpu 20 edge-time 2.260600e-02  eps-prime 1.000000e-06  push-cpu-time 7.785586e+01  push-wall-time 4.310349e+00  t-cpu-time 1.176852e+02 t-wall-time 4.421390e+01
snapshot 2 #edges 751 cpu 20 edge-time 3.215000e-02  eps-prime 1.000000e-06  push-cpu-time 1.535421e+02  push-wall-time 8.489356e+00  t-cpu-time 1.933810e+02 t-wall-time 4.840527e+01
snapshot 3 #edges 1198 cpu 20 edge-time 4.170900e-02  eps-prime 1.000000e-06  push-cpu-time 2.650497e+02  push-wall-time 1.460841e+01  t-cpu-time 3.048983e+02 t-wall-time 5.453632e+01
snapshot 4 #edges 1659 cpu 20 edge-time 5.156900e-02  eps-prime 1.000000e-06  push-cpu-time 4.270176e+02  push-wall-time 2.333157e+01  t-cpu-time 4.668762e+02 t-wall-time 6.326983e+01
[1]    3299550 killed     code/dynamic-ppe-fast datasets/academic-small/config_t_36_d_512/ 512 0.1 0.15

With the help of htop command, The killed reason is out of memory, by the way, my running environment is CentOS 8 with 256GB memory.

Best wishes.

**Comment by zjlxgxz** [comment]
Hey @storyandwine, thanks for reporting it. We will take a closer look about the memory issue. 
But you can try to use a larger esp to unblock it (say 0.5, but may yield less good embedding quality).

**Comment by zjlxgxz** [comment]
@storyandwine, the sample code fixed the max node ID size, for the graphs <100k nodes, you may make this value small. Does it solve the memory issue? 

https://github.com/zjlxgxz/DynamicPPE/blob/855d645340f92a6ae3473bdb504588159b441d3e/code/dynamic_ppe_fast.cpp#L58

**Comment by storyandwine** [comment]
Thanks for your enthusiastic response, but these do not seem to work for me.
After using larger esp (0.5 and 1.0), it is still OOM after snapshot 4.
MAX_NODE_ID seems to be useful, but still couldn't running completely.
For detail:
MAX_NODE_ID 3250000 which is half of the default value, it can run up to snapshot 7, and OOM.

snapshot 7 #edges 4059 cpu 20 edge-time 4.734200e-02  eps-prime 1.000000e-06  push-cpu-time 5.705568e+02  push-wall-time 3.129107e+01  t-cpu-time 6.116148e+02 t-wall-time 7.244620e+01
[1]    3869536 killed     code/dynamic-ppe-fast datasets/academic-small/config_t_36_d_512 512 0.1 0.15

MAX_NODE_ID 1750000 can goes to snapshot 10.

When further reducing the MAX_NODE_ID to 850000, other errors have occurred.

dynamic-ppe-fast: dynamic_ppe_fast.cpp:238: void calculate_emb(int): Assertion `estimators.find(s) != estimators.end()' failed.
[1]    3873738 abort (core dumped)  code/dynamic-ppe-fast datasets/academic-small/config_t_36_d_512 512 0.1 0.15

I'm guessing it might be caused by the previous snapshot memory not being freed properly?
Of course, it is also possible that the 256G memory can not keep up with the times. In this regard, I would like to get your further help on this, e.g. how many nodes of the graph in your experiments would require approximately how much memory consumption. 

Best regards.

**Comment by zjlxgxz** [comment]
We are sorry for not testing it extensively. The memory depends on how many nodes we want to keep track. For reference, our cluster has ~1.5TB memory for the experiments. For the sample graph, set MAX_NODE_ID: 100000 should be good.

About the new error, I will check the uploaded version, it seems a runtime multi-thread issue. 

BTW, I just had a quick test on my personal PC with a subset of last 10K nodes. It worked well and took ~18mins on a single cpu with ~16GB memory used. You can truncate nodes before 40K in the target_nodes.txt or use single cpu to try it first . e,g, change the range of target nodes in the following file, and set with num_cpus=1:
https://github.com/zjlxgxz/DynamicPPE/blob/855d645340f92a6ae3473bdb504588159b441d3e/datasets/academic-small/config_t_36_d_48/target_nodes.txt#L40000

**Comment by storyandwine** [comment]
Thanks a lot, set with num_cpus=1 works for me!
